/* eslint-disable react/no-unescaped-entities */
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


import Header  from "./components/header";
import PageTransition from "./components/PageTransitions";
import StairTransition from "./components/StairTransition";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       

  <body
    className={`${geistSans.variable} ${geistMono.variable} antialiased`}
  >
    <div className="mx-4 xl:mx-12 my-6">
      <Header /> 
      <StairTransition />
      <PageTransition>
        {children}
      </PageTransition>
    </div>
  </body>
</html>

  );
}
